//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18047
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenVPNManager.lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenVPNManager.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not communicate with OpenVPN Manager - perhaps remote control is not allowed?.
        /// </summary>
        internal static string ARGS_Error {
            get {
                return ResourceManager.GetString("ARGS_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -install-autostart   -   Install autostart and quit
        ///-remove-autostart   -   Remove autostart and quit
        ///-connect name   -   Connect to VPN &quot;name&quot;
        ///-disconnect name   -   Disconnect from VPN &quot;name&quot;
        ///-quit   -   Shut down running OpenVPN Manager
        ///
        ///-install   -   install OpenVPNManager service
        ///-uninstall   -   uninstall OpenVPNManager service
        ///-ExecuteServiceAsConsole   -   Run the &apos;service&apos; as a console program.
        /// </summary>
        internal static string ARGS_Help {
            get {
                return ResourceManager.GetString("ARGS_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid value &quot;{1}&quot; for argument {0}!
        ///Valid values are:
        ///{2}.
        /// </summary>
        internal static string ARGS_Invalid_Parameter {
            get {
                return ResourceManager.GetString("ARGS_Invalid_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing value for argument &quot;{0}&quot;.
        /// </summary>
        internal static string ARGS_Missing_Parameter {
            get {
                return ResourceManager.GetString("ARGS_Missing_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown argument &quot;{0}&quot;.
        /// </summary>
        internal static string ARGS_Unknown_Parameter {
            get {
                return ResourceManager.GetString("ARGS_Unknown_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not load Config file. Ignoring!.
        /// </summary>
        internal static string BOX_Config_Error {
            get {
                return ResourceManager.GetString("BOX_Config_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The configuration could not be saved to file due to an internal error.
        /// </summary>
        internal static string BOX_Config_Not_Saved {
            get {
                return ResourceManager.GetString("BOX_Config_Not_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The configuration requires a proxy server, but no address is provided..
        /// </summary>
        internal static string BOX_Config_Proxy_Address_Missing {
            get {
                return ResourceManager.GetString("BOX_Config_Proxy_Address_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to connect!
        ///
        ///Details:.
        /// </summary>
        internal static string BOX_Error_Connect {
            get {
                return ResourceManager.GetString("BOX_Error_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while loading configuration:.
        /// </summary>
        internal static string BOX_Error_Information {
            get {
                return ResourceManager.GetString("BOX_Error_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not find smart card. Please insert one and press retry..
        /// </summary>
        internal static string BOX_NoKey {
            get {
                return ResourceManager.GetString("BOX_NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to reconnect to this VPN?.
        /// </summary>
        internal static string BOX_Reconnect {
            get {
                return ResourceManager.GetString("BOX_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à These settings are saved in the registry. You can change them with administrator rights.
        ///They are located in HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN..
        /// </summary>
        internal static string BOX_Service_How_Change {
            get {
                return ResourceManager.GetString("BOX_Service_How_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The OpenVPN service is not installed.
        /// </summary>
        internal static string BOX_Service_Not_Installed {
            get {
                return ResourceManager.GetString("BOX_Service_Not_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OpenVPN Manager and the OpenVPN service are using the same directory.
        ///OpenVPN Manager can&apos;t figure out how the connections should be controlled, so the service control features are deactivated.
        ///Change one of the directories or change the service file extension..
        /// </summary>
        internal static string BOX_Service_Same_Path {
            get {
                return ResourceManager.GetString("BOX_Service_Same_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In order to edit settings all connection must be closed. Close all connections?.
        /// </summary>
        internal static string BOX_Settings_Close {
            get {
                return ResourceManager.GetString("BOX_Settings_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The update information could not be downloaded.
        /// </summary>
        internal static string BOX_UpdateError {
            get {
                return ResourceManager.GetString("BOX_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The update information hat an invalid format.
        /// </summary>
        internal static string BOX_UpdateFormat {
            get {
                return ResourceManager.GetString("BOX_UpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new Version (%s) was found. Do you want to see details in your browser?.
        /// </summary>
        internal static string BOX_UpdateInformation {
            get {
                return ResourceManager.GetString("BOX_UpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The update information did not contain this program!.
        /// </summary>
        internal static string BOX_UpdateMissing {
            get {
                return ResourceManager.GetString("BOX_UpdateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No new version was found..
        /// </summary>
        internal static string BOX_UpdateNone {
            get {
                return ResourceManager.GetString("BOX_UpdateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The location of the OpenVPN binary changed.
        ///
        ///Please also update the service (using the service tab) if the
        ///service should also use the new location..
        /// </summary>
        internal static string BOX_UpdateService {
            get {
                return ResourceManager.GetString("BOX_UpdateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The configuration file of this connection is not supported by OpenVPN Manager configuration interface. 
        ///
        ///Do you want to Edit the configuration in with Notepad ?.
        /// </summary>
        internal static string BOX_VPN_Config_Not_Supported {
            get {
                return ResourceManager.GetString("BOX_VPN_Config_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while starting OpenVPN. Do you want to see its log file?.
        /// </summary>
        internal static string BOX_VPN_Error {
            get {
                return ResourceManager.GetString("BOX_VPN_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while starting OpenVPN..
        /// </summary>
        internal static string BOX_VPNS_Error {
            get {
                return ResourceManager.GetString("BOX_VPNS_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à disabled.
        /// </summary>
        internal static string DIALOG_Disabled {
            get {
                return ResourceManager.GetString("DIALOG_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à enabled.
        /// </summary>
        internal static string DIALOG_Enabled {
            get {
                return ResourceManager.GetString("DIALOG_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All files.
        /// </summary>
        internal static string DIALOG_Filter_Allfiles {
            get {
                return ResourceManager.GetString("DIALOG_Filter_Allfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Applications.
        /// </summary>
        internal static string DIALOG_Filter_Application {
            get {
                return ResourceManager.GetString("DIALOG_Filter_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Copy IP.
        /// </summary>
        internal static string DIALOG_IP_Copy {
            get {
                return ResourceManager.GetString("DIALOG_IP_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à service.
        /// </summary>
        internal static string DIALOG_Service {
            get {
                return ResourceManager.GetString("DIALOG_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select OpenVPN configuration directory.
        /// </summary>
        internal static string DIALOG_Title_Folder {
            get {
                return ResourceManager.GetString("DIALOG_Title_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select CA certificate file.
        /// </summary>
        internal static string DIALOG_Title_Open_CACert {
            get {
                return ResourceManager.GetString("DIALOG_Title_Open_CACert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the key file for additional TLS authentication.
        /// </summary>
        internal static string DIALOG_Title_Open_KeyFile {
            get {
                return ResourceManager.GetString("DIALOG_Title_Open_KeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search OpenVPN.
        /// </summary>
        internal static string DIALOG_Title_Open_OpenVPN {
            get {
                return ResourceManager.GetString("DIALOG_Title_Open_OpenVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select private key file.
        /// </summary>
        internal static string DIALOG_Title_Open_PrivateKey {
            get {
                return ResourceManager.GetString("DIALOG_Title_Open_PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the secret static key file.
        /// </summary>
        internal static string DIALOG_Title_Open_StaticKey {
            get {
                return ResourceManager.GetString("DIALOG_Title_Open_StaticKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select user certificate file.
        /// </summary>
        internal static string DIALOG_Title_Open_UserCert {
            get {
                return ResourceManager.GetString("DIALOG_Title_Open_UserCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect (Alt+O).
        /// </summary>
        internal static string QUICKINFO_Connect {
            get {
                return ResourceManager.GetString("QUICKINFO_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnect (Alt+O).
        /// </summary>
        internal static string QUICKINFO_Disconnect {
            get {
                return ResourceManager.GetString("QUICKINFO_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An Update is available!.
        /// </summary>
        internal static string QUICKINFO_Update {
            get {
                return ResourceManager.GetString("QUICKINFO_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See the &quot;about&quot; Dialog for more information..
        /// </summary>
        internal static string QUICKINFO_Update_More {
            get {
                return ResourceManager.GetString("QUICKINFO_Update_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected.
        /// </summary>
        internal static string STATE_Connected {
            get {
                return ResourceManager.GetString("STATE_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connecting.
        /// </summary>
        internal static string STATE_Connecting {
            get {
                return ResourceManager.GetString("STATE_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnected.
        /// </summary>
        internal static string STATE_Disconnected {
            get {
                return ResourceManager.GetString("STATE_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string STATE_Error {
            get {
                return ResourceManager.GetString("STATE_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initializing....
        /// </summary>
        internal static string STATE_Initializing {
            get {
                return ResourceManager.GetString("STATE_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stopped.
        /// </summary>
        internal static string STATE_Stopped {
            get {
                return ResourceManager.GetString("STATE_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stopping....
        /// </summary>
        internal static string STATE_Stopping {
            get {
                return ResourceManager.GetString("STATE_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Connect.
        /// </summary>
        internal static string TRAY_Connect {
            get {
                return ResourceManager.GetString("TRAY_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Disconnect.
        /// </summary>
        internal static string TRAY_Disconnect {
            get {
                return ResourceManager.GetString("TRAY_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Edit.
        /// </summary>
        internal static string TRAY_Edit {
            get {
                return ResourceManager.GetString("TRAY_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show &amp;error information.
        /// </summary>
        internal static string TRAY_Error_Information {
            get {
                return ResourceManager.GetString("TRAY_Error_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Show.
        /// </summary>
        internal static string TRAY_Show {
            get {
                return ResourceManager.GetString("TRAY_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adding routes....
        /// </summary>
        internal static string VPNSTATE_ADD_ROUTES {
            get {
                return ResourceManager.GetString("VPNSTATE_ADD_ROUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assigning IP....
        /// </summary>
        internal static string VPNSTATE_ASSIGN_IP {
            get {
                return ResourceManager.GetString("VPNSTATE_ASSIGN_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authenticating....
        /// </summary>
        internal static string VPNSTATE_AUTH {
            get {
                return ResourceManager.GetString("VPNSTATE_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected.
        /// </summary>
        internal static string VPNSTATE_CONNECTED {
            get {
                return ResourceManager.GetString("VPNSTATE_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connecting....
        /// </summary>
        internal static string VPNSTATE_CONNECTING {
            get {
                return ResourceManager.GetString("VPNSTATE_CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exiting....
        /// </summary>
        internal static string VPNSTATE_EXITING {
            get {
                return ResourceManager.GetString("VPNSTATE_EXITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloading config....
        /// </summary>
        internal static string VPNSTATE_GET_CONFIG {
            get {
                return ResourceManager.GetString("VPNSTATE_GET_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reconnecting....
        /// </summary>
        internal static string VPNSTATE_RECONNECTING {
            get {
                return ResourceManager.GetString("VPNSTATE_RECONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiting for Server....
        /// </summary>
        internal static string VPNSTATE_WAIT {
            get {
                return ResourceManager.GetString("VPNSTATE_WAIT", resourceCulture);
            }
        }
    }
}
